routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Post;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'Controller@aboutMe');

//LostinTaste Module
Route::prefix('lostintaste')->name('lostintaste.')->group(function() {
    
    // welcome's route
    Route::get('/', 'LostinTaste\HomeController@index')->name('welcome');
    Route::get('searcher', 'LostinTaste\HomeController@search')->name('searcher');
    Route::get('getprovince/{district}', 'LostinTaste\HomeController@getProvince');
    Route::get('getfood', 'LostinTaste\HomeController@getFood');

    // user's routes
    Route::get('me', 'LostinTaste\HomeController@selfInfo')->name('self_info');
    Route::get('profile/{id}', 'LostinTaste\HomeController@userProfile')->name('profile');
    Route::get('update/user/{id}', 'LostinTaste\HomeController@updateUser')->name('update_user');
    Route::post('update/user', 'LostinTaste\HomeController@insertUser')->name('insert_user');

    // news's routes
    Route::get('news', 'LostinTaste\HomeController@news')->name('news');
    Route::get('attend/{id}', 'LostinTaste\HomeController@attend');

    // post's routes
    Route::get('post', 'LostinTaste\HomeController@post')->name('post');
    Route::get('newpost', 'LostinTaste\HomeController@newPost')->name('new_post');
    Route::get('update/post/{id}', 'LostinTaste\HomeController@updatePost');
    Route::post('insertpost', 'LostinTaste\HomeController@insertPost')->name('insert_post');
    Route::get('delete/post/{id}', 'LostinTaste\HomeController@deletePost');

    // savedpost's routes
    Route::get('savedpost', 'LostinTaste\HomeController@savedpost')->name('savedpost');
    Route::get('newsavedpost/{id}', 'LostinTaste\HomeController@newSavedpost');
    Route::get('update/savedpost/{id}/{mode}', 'LostinTaste\HomeController@updateSavedpost');
    Route::get('delete/savedpost/{id}', 'LostinTaste\HomeController@deleteSavedpost');

    // schedule's routes
    Route::get('schedule', 'LostinTaste\HomeController@schedule')->name('schedule');
    Route::get('newschedule/{id}', 'LostinTaste\HomeController@newSchedule');
    Route::get('update/schedule/{id}', 'LostinTaste\HomeController@updateSchedule');
    Route::post('insertschedule', 'LostinTaste\HomeController@insertSchedule')->name('insert_schedule');
    Route::get('delete/schedule/{id}', 'LostinTaste\HomeController@deleteSchedule');

    Route::get('delete/attendee/{id}', 'LostinTaste\HomeController@deleteAttendee')->name('delete_attendee');

    // friend's routes
    Route::get('friend', 'LostinTaste\HomeController@friend')->name('friend');
    Route::get('search-friend/{input?}', 'LostinTaste\HomeController@searchFriend')->name('search_friend');
    Route::get('addfriend/{id}', 'LostinTaste\HomeController@addfriend')->name('add_friend');
    Route::get('dropfriend/{id}', 'LostinTaste\HomeController@dropfriend')->name('drop_friend');

    // message's routes
    Route::get('message', 'LostinTaste\HomeController@message')->name('message');
    Route::get('inbox/{id?}', 'LostinTaste\HomeController@inbox')->name('inbox');
    Route::get('sendmessage', 'LostinTaste\HomeController@sendMessage')->name('send_message');
    Route::get('refresh/{id}', 'LostinTaste\HomeController@refresh')->name('refresh');

});

app/Models/LostinTaste/Attendee.php
<?php

namespace App\Models\LostinTaste;

use Illuminate\Database\Eloquent\Model;

class Attendee extends Model
{
    protected $guard = [];
    protected $fillable = ['user_id', 'schedule_id'];
    public $timestamps= true;

    public function User(){
        return $this->belongsto('App\User');
    }
    
    public function Schedule(){
        return $this->belongsTo('App\Models\LostinTaste\Schedule');
    }
    
}

app/Models/LostinTaste/Info.php
<?php

namespace App\Models\LostinTaste;

use Illuminate\Database\Eloquent\Model;

class Info extends Model
{
    protected $fillable = ['user_id'];

    public function User(){
        return $this->belongsto('App\User'); // need to stay because User must be outside of module
    }
}

app/Models/LostinTaste/Message.php
<?php

namespace App\Models\LostinTaste;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    public function Subject(){
        return $this->belongsto('App\User','subject_id');
    }
    public function Object(){
        return $this->belongsto('App\User','object_id');
    }
}

app/Models/LostinTaste/Post.php
<?php

namespace App\Models\LostinTaste;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guard = [];

    protected $fillable = ['name', 'kind', 'price', 'district', 'province', 'address', 'picture', 'time', 'user_id'];

    public $timestamps= true;

    public function User(){
        return $this->belongsto('App\User');
    }

    public function SavedPost(){
        return $this->hasMany('App\Models\LostinTaste\SavedPost');
    }

    public function Schedule(){
        return $this->hasMany('App\Models\LostinTaste\Schedule');
    }

    public static function boot() {
        parent::boot();

        static::deleting(function($post) { // before delete() method call this
             foreach($post->savedpost as $savedpost){
                 $savedpost->delete();
             }
             foreach($post->schedule as $schedule){
                 $schedule->delete();
             }
        });
    }
}

app/Models/LostinTaste/SavedPost.php
<?php

namespace App\Models\LostinTaste;

use Illuminate\Database\Eloquent\Model;

class SavedPost extends Model
{
    protected $guard = [];
    protected $fillable = ['mode', 'user_id', 'post_id'];
    public $timestamps = true;

    public function User(){
        return $this->belongsto('App\User');
    }
    
    public function Post(){
        return $this->belongsTo('App\Models\LostinTaste\Post');
    }
    
}

app/Models/LostinTaste/Schedule.php
<?php

namespace App\Models\LostinTaste;

use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{
    protected $fillable = ['time', 'mode', 'user_id', 'post_id'];
    
    public function User(){
        return $this->belongsto('App\User');
    }

    public function Post(){
        return $this->belongsTo('App\Models\LostinTaste\Post');
    }

    public function Attendee(){
        return $this->hasMany('App\Models\LostinTaste\Attendee');
    }

    public static function boot() {
        parent::boot();

        static::deleting(function($schedule) { // before delete() method call this
             foreach($schedule->attendee as $attendee){
                 $attendee->delete();
             }
        });
    }
}

app/Http/Controllers/LostinTaste/HomeController.php
<?php

namespace App\Http\Controllers\LostinTaste;

use Illuminate\Http\Request;
use App\Services\LostinTaste\QueryService;
use App\Services\InitDataBase;
use Illuminate\Routing\Controller;
use DB;
use Storage;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    protected $queryService;

    public function __construct(QueryService $queryService)
    {
        $this->middleware('auth')->except(['index', 'search', 'getProvince', 'getFood']);
        $this->queryService = $queryService;
        new InitDataBase();
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    // Welcome Controller
    public function index(){
        $var['topfoods'] = $this->queryService->getCheapestPost();
        return view('lostintaste.welcome', $var);
    }

    public function search(){
        return view('lostintaste.searcher');
    }

    public function getProvince($district){
        return DB::table('hanoidistrict')
        ->where('district', '=', $district)
        ->select('province')
        ->get();
    }

    public function getFood(Request $request){
        $data = $this->queryService->getPostWithUser()->where('price', '<', $request->price);

        if($request->kind != "Tất cả") $data = $data->where('kind', '=', $request->kind);
        if($request->district != "Tất cả") $data = $data->where('district', '=', $request->district);
        if($request->province != "Tất cả") $data = $data->where('province', '=', $request->province);
        return $data->orderBy('id','DESC')->get();
    }
    // User Controller
    public function selfInfo(){
        $this->queryService->createUserInfo();
        $var['user'] = auth()->user();
        return view('lostintaste.me', $var);
    }

    public function userProfile($id){
        $var['user'] = $this->queryService->findUser($id);
        $var['post'] = $var['user']->post()->with('user', 'user.info')->paginate(4);
        return view('lostintaste.personal.profile', $var);
    }

    public function updateUser($id){
        $var['user'] = $this->queryService->findUser($id);
        return view('lostintaste.personal.update-user', $var);
    }

    public function insertUser(Request $request){
        $userId = auth()->user()->id;
        if($request['is_link']){
            $filename = $userId . '.png';
            if($request->avatar) Storage::putFileAs('public/user-avatar', $request->avatar, $filename);
        }
        else{
            // check for valid file
            if ($request->hasFile('avatar')) {
                if ($request->file('avatar')->isValid()) {
                    $filename = $userId . $request->avatar->extension();
                    $request->avatar->storeAs('public/user-avatar', $filename);
                }
            }
        }
        $array = [
            'birthdate' => $request->birthdate,
            'workplace' => $request->workplace,
            'avatar' => '/user-avatar/' . $filename,
        ];
        $this->queryService->updateUser($array);
        return redirect()->route('lostintaste.self_info');
    }

    // Post Controller
    public function post(){
        $var['post'] = $this->queryService->readPost();
        return view('lostintaste.personal.post', $var);
    }

    public function newPost(){
        return view('lostintaste.personal.new-post');
    }

    public function updatePost($id){
         $var['post'] = $this->queryService->findPost($id);
        return view('lostintaste.personal.new-post', $var);
    }

    public function insertPost(Request $request){
        if($request['id'] != ''){
            // update
            $postId = $request['id'];
            $array = $request->all();
        }else{
            // create
            $request['user_id'] = auth()->user()->id;
            $post = $this->queryService->createPost($request->except('picture'));
            $postId = $post->id;
        }

        if($request['is_link'] && (strlen($request->picture) > 0 && $request->picture[0] != '/')){ // is an absolute link
            $filename = $postId . '.png';
            if($request->picture) Storage::putFileAs('public/post-picture', $request->picture, $filename);
        }
        else{
            // check for valid file
            if ($request->hasFile('picture')) {
                if ($request->file('picture')->isValid()) {
                    $filename = $postId . $request->picture->extension();
                    $request->picture->storeAs('public/post-picture', $filename);
                }
            }
        }
        $array['id'] = $postId;
        if(isset($filename)) $array['picture'] = '/post-picture/' . $filename; // if there is no file, then dont update picture
        else unset($array['picture']);
        $this->queryService->updatePost($array);

        return redirect()->route('lostintaste.post'); 
    }

    public function deletePost($id){
        $this->queryService->deletePost($id);
        return back();
    }

    // Savedpost Controller
    public function savedpost()
    {
        $var['savedpost'] = $this->queryService->readSavedpost();
        return view('lostintaste.personal.savedpost', $var);
    }

    public function newSavedpost($id){
        $user = auth()->user();
        if(count($user->savedpost
        ->where('post_id', '=', $id)) == 0){
            $this->queryService->createSavedpost([
                'mode' => 'Tất cả',
                'user_id' => $user->id,
                'post_id' => $id,
            ]);
            return 1;
        }
        return 0;
    }
    public function updateSavedpost($id, $mode){
        $this->queryService->updateSavedpost($id, $mode);
        return back();
    }

    public function deleteSavedpost($id){
        $this->queryService->deleteSavedpost($id);
        return back();
    }

    // Schedule Controller
    public function schedule()
    {
        $var['schedule'] = $this->queryService->readSchedule();
        $var['attended'] = auth()->user()->attended;
        return view('lostintaste.personal.schedule', $var);
    }
    
    public function newSchedule($id){
        $var['post'] = $this->queryService->findPost($id);
        return view('lostintaste.personal.new-schedule', $var);
    }

    public function updateSchedule($id){
        $var['schedule'] = $this->queryService->findSchedule($id);
        $var['post'] = $var['schedule']->post;
        return view('lostintaste.personal.new-schedule', $var);
    }

    public function insertSchedule(Request $request){
        if($request->id != ''){
            $this->queryService->updateSchedule($request->only('id', 'time', 'mode'));
        }else{
            $request['user_id'] = auth()->user()->id;
            $this->queryService->createSchedule($request->all());
        }
        return redirect()->route('lostintaste.schedule');
    }
    
    public function deleteSchedule($id){
        $this->queryService->deleteSchedule($id);
        return back();
    }

    public function deleteAttendee($id){
        $this->queryService->deleteAttendee($id);
        return back();
    }

    // News Controller
    public function news(){
        $var['news'] = $this->queryService->publicSchedule();
        return view('lostintaste.personal.news', $var);
    }

    public function attend($id){
        $user = auth()->user();
        if(!$this->queryService->hasAttended($user->id, $id)){
            $this->queryService->createAttendee([
                'user_id' => $user->id,
                'schedule_id' => $id
                ]);
            return 1;
        }
        return 0;
    }

    // Friend Controller
    public function friend()
    {
        $var['user'] = auth()->user();
        $var['friend'] = $var['user']->friend;
        
        $var['mightknow'] = collect();
        $savedpost = auth()->user()->savedpost;
        foreach($savedpost as $sp){
            $postsaver = $sp->post->savedpost;
            foreach($postsaver as $saver){
                $var['mightknow']->push($saver->user);
            }
        }
        $var['mightknow'] = $var['mightknow']->unique('id');
        return view('lostintaste.personal.friend', $var);
    }

    public function searchFriend($input){
        return $this->queryService->findUserByName($input);
    }

    public function addfriend($id){
        $userId = auth()->user()->id;
        $friend = DB::table('friend')
        ->where('subject_id', '=', $userId)
        ->where('object_id', '=', $id)->get();
        if(count($friend) == 0){
            DB::table('friend')->insert([
            "subject_id" => $userId,
            "object_id" => $id
            ]);
            return 1;
        }
        return 0;
    }

    public function dropfriend($id){
        $userId = auth()->user()->id;
        $friend = DB::table('friend')
        ->where('subject_id', '=', $userId)
        ->where('object_id', '=', $id)->get();
        if(count($friend) != 0){
            DB::table('friend')
            ->where('subject_id', '=', $userId)
            ->where('object_id', '=', $id)->delete();
            return 1;
        }
        return 0;
    }

    // Message Controller
    public function message(){
        $var['message'] = $this->queryService->getAllMessages();
        return view('lostintaste.personal.message', $var);
    }

    public function inbox($id){
        $var['object'] =  $this->queryService->findUser($id);
        $var['inbox'] = $this->queryService->getMessageWith($id);
        $var['inbox'] = $var['inbox']->sortBy('id');
        return view('lostintaste.personal.inbox', $var);
    }

    public function sendMessage(Request $request) {
        $data['content'] = $request->content;
        $data['subject_id'] = auth()->user()->id;
        $data['object_id'] = $request->id;
        $this->queryService->createMessage($data);
    }

    public function refresh($id) {

resources/views/lostintaste/personal/friend.blade.php
@extends('lostintaste.layouts.nav')
@section('undernav')
<br>
<div class="card">
    <input id="friendSearch" onkeyup="searchFriend()" type="text" class="form-control" placeholder="Tìm bạn bè">
    <div id="friendShow" class="z-index"></div>
</div>
<br>
<br>
<div class="card dropdown">
    <div class="card-header">Your Friends</div>
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Show
    </button>
    <div class="dropdown-menu container" aria-labelledby="dropdownMenu1">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">Bạn có thể quen</div>
                    @foreach($mightknow as $f)
                        <div><a href="{{ route('lostintaste.profile', ['id' => $f->id]) }}"><img width="10%" heigth="10%" class="rounded-circle" src="{{$f->info->avatar??""}}">{{$f->name??""}}</a></div>
                    @endforeach
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-header">Your Friends</div>
                    @foreach($friend as $f)
                        <div><a href="{{ route('lostintaste.profile', ['id' => $f->id]) }}"><img width="10%" heigth="10%" class="rounded-circle" src="{{$f->info->avatar}}">{{$f->name}}</a></div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="card">
    <div class="card-header">Your Friends Post</div>
    Chưa hoàn thành
</div>
@endsection

@section('script')
    <script>
        const searchFriend = () => {
            const input = document.getElementById("friendSearch");
            const output = document.getElementById("friendShow");
            if(input.value != ""){
                axios.get("{{ route('lostintaste.search_friend') }}/" + input.value)
                .then(
                    (response) => {
                        output.innerHTML = "";
                        for(var i=0; i<response.data.length;i++){
                            output.innerHTML += 
                            "<a href='profile/" + response.data[i].id + "'>"
                                + response.data[i].name + 
                            "</a><br>";
                        }
                    }
                )
                .catch(
                    (error)=>{
                        console.log(error);
                    }
                )
            }
            else output.innerHTML = "";
        }
    </script>
@endsection

resources/views/lostintaste/personal/inbox.blade.php
@extends('lostintaste.layouts.nav')
@section('undernav')
<br>
Chưa hoàn thành
{{--  cần tối ưu  --}}
{{--  <div class="card" onmousemove="setId({{ $object->id }})">
    <div class="card-header">
        <div class="card-header">{{ $object->name }}<br>
            <a href="#last"><button id="golast" class="btn-primary">xuống cuối</button></a></div>
    </div>
    <div class="card-body" id="msg-container" onscroll="setId({{ $object->id }})" style="height:500px; overflow: scroll">
        <div id="messageshow">
            @foreach($inbox as $i)
            @if($i->subject->id == auth()->user()->id)
            <div class="row justify-content-end">
                <span class="badge-primary rounded shadow mb-1">{{ $i->content }}</span><img width="10%" heigth="10%" class="rounded-circle" src="{{$i->subject->info->avatar}}"><br>
            </div>
            @else
            <div class="row justify-content-start">
                <img width="10%" heigth="10%" class="rounded-circle" src="{{ $i->subject->info->avatar }}"><span class="alert-warning rounded shadow mb-1">{{$i->content}}</span><br>   
            </div>
                @endif
            @endforeach
        </div>
        <div id='last'></div>
    </div>
    <div class="input-group">
        <input id="message" onkeyup="enter(event, {{ $object->id }})" type="text" class="form-control" aria-describedby="basic-addon1">
        <div class="input-group-append">
            <button id="send-btn" onclick="send({{ $object->id }})" class="btn btn-primary" type="button">Send</button>
        </div>
    </div>
</div>  --}}
@endsection

@section('script')
    <script>
        const msg = document.getElementById('messageshow');
        const msgCon = document.getElementById('msg-container');
        setTimeout(function(){
            document.getElementById('golast').click();
        }, 50);
        var obj_id;
        setInterval(function(){
            if(obj_id != undefined){
                if(msgCon.scrollTop + msgCon.clientHeight >= msgCon.scrollHeight * 9 / 10){
                    refresh(obj_id);
                }
            }
        }, 1000);
        msgCon = document.getElementById('msg-container');
        msgCon.scrollTop = msgCon.scrollHeight-msgCon.clientHeight;
            
        const setId = (id) => {
            obj_id = id;
        }

        const refresh = (id) => {
            axios.get("/refresh/"+id)
            .then(
                (response) => {
                    msg.innerHTML = "";
                    const res = response.data;
                    var minindex = 0, i = 0;
                    while(Object.keys(res).length > 0){
                        for(var index in res){
                            if(res[minindex] == undefined || res[minindex].id > res[index].id) minindex = index;
                        }
                        print(id, res[minindex]);
                        delete res[minindex];
                    }
                }
            )
            .catch(
                (error) => {
                    console.log(error);
                }
            )
        }
        
        const print = (id, resmin) => {
            if(resmin.subject_id == id){
                msg.innerHTML +=
                "<div class='row justify-content-start'>"
                    + "<img width='10%' heigth='10%' class='rounded-circle' src='{{ $object->info->avatar ?? "" }}'><span class='alert-warning rounded shadow mb-1'>"
                        + resmin.content
                        + "</span><br>"   
                + "</div>";
            }
            else{
                msg.innerHTML +=
                "<div class='row justify-content-end'>"
                    + "<span class='badge-primary rounded shadow mb-1'>"
                        + resmin.content
                        + "</span><img width='10%' heigth='10%' class='rounded-circle' src='{{ auth()->user()->info->avatar ?? "" }}'><br>"
                + "</div>";
            }
        }
        const enter = (event, id) => {
            if(event.keyCode == 13){
                send(id);
            }
        }
        const send = (id) => {
            const message = document.getElementById('message');
            msg.scrollTop = msg.scrollHeight;
            axios.get("{{ route('lostintaste.send_message') }}?id="+id+"&content="+message.value)
            .then(
                (response) => {
                    message.value = "";
                }
            )
            .catch(
                (error) => {
                    console.log(error);
                }
            )
        }
    <script>
@endsection

resources/views/lostintaste/personal/profile.blade.php
@extends('lostintaste.layouts.app')
@section('content')
<div class="card">
    <img class="card-img-top" src="{{ $user->info->avatar }}" alt="Food lấu đồ ăn">
    <div class="card-body">
        <h4 class="card-title">{{ $user->name }}</h4>
        <div class="card-text">
            <div class="row justify-content-start">Ngày sinh:{{ $user->info->birthdate }}</div>
            <br>
            <div class="row justify-content-start">Trường học/Công ty:{{ $user->info->workplace }}</div>
            <br>
        </div>
    </div>
    <div class="row">
        <div class="col"><button id="addfriend-btn" onclick="addfriend({{ $user->id }})" style="width: 100%" class="btn btn-outline-primary">Kết bạn</button></div>
        <div class="col"><button id="dropfriend-btn" onclick="dropfriend({{ $user->id }})" style="width: 100%" class="btn btn-outline-danger">Hủy kết bạn</button></div>
        <div class="col"><a href="{{ route('lostintaste.inbox', ['id' => $user->id]) }}"><button style="width: 100%" class="btn btn-outline-primary">Nhắn tin</button></a></div>
    </div>
</div>
<br>
<div class="card">
</div>
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col">{{ $user->name }} Posts</div>
        </div>
    </div>
    <div class="card-body">
        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif
        <div class="row" style="">{{ $post->links() }}</div>
        <Post 
            v-for="(data) in {{ json_encode($post->items()) }}" 
            :key="data.id" 
            :propdata="data"
            page="profile" 
        />
        <div class="row">{{ $post->links() }}</div>
    </div>
</div>
<br>
<br>
<div class="card dropdown">
    <div class="card-header">{{ $user->name }} Saved Post</div>
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Show
    </button>
    <div class="dropdown-menu bg-danger" aria-labelledby="dropdownMenu1">
        Chưa hoàn thiện
    </div>
</div>
@endsection

@section('script')
    <script>
        const addfriend = (id) => {
            document.getElementById('addfriend-btn').innerHTML = "Đã kết bạn";
            document.getElementById('dropfriend-btn').innerHTML = "Hủy kết bạn";
            axios.get("{{ route('lostintaste.add_friend') }}"+id)
            .then(
                (response)=>{
                    if(response.data == 0){
                        alert("Bạn đã kết bạn với người này");
                    }
                }
            )
            .catch(
                (error)=>{
                    console.log(error);
                }
            )
        }
        const dropfriend=(id)=>{
            document.getElementById('dropfriend-btn').innerHTML="Đã hủy";
            document.getElementById('addfriend-btn').innerHTML="Kết bạn";
            axios.get("{{ route('lostintaste.add_friend') }}"+id)
            .then(
                (response)=>{
                    if(response.data == 0){
                        alert("Bạn chưa kết bạn với người này");
                    }
                }
            )
            .catch(
                (error)=>{
                    console.log(error);
                }
            )
        }
    </script>
@endsection

resources/views/lostintaste/personal/schedule.blade.php
@extends('lostintaste.layouts.nav')
@section('undernav')
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col"></div>
                <div class="col">Your Schedule</div>
                <div class="col"></div>
            </div>
        </div>
        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            @endif
            <div class="row">
                <div class="col"></div>
                <div class="">{{ $schedule->links() }}</div>
                <div class="col"></div>
            </div>
            <Post 
                v-for="(data) in {{ json_encode($schedule->items()) }}" 
                :key="data.id" 
                :propdata="data"
                page="schedule" 
            />
            <div class="row">
                <div class="col"></div>
                <div class="">{{ $schedule->links() }}</div>
                <div class="col"></div>
            </div>
        </div>
    </div>
    <br>
    <div class="card dropdown">
        <div class="card-header">Attended</div>
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Show
        </button>
        <div class="dropdown-menu container" aria-labelledby="dropdownMenu1">
            @foreach($attended as $a)
            <br>
            <div class="card">
                <img class="card-img-top" 
                src="{{ $a->schedule->post->picture }}" width="100%" height="100%">
                <div class="card-body">
                    <h2>Tên: {{ $a->schedule->post->name }}</h2>
                    <div style="">
                    <div><b>Giá:</b> {{ $a->schedule->post->price }}000 VND</div>
                    <br>
                    <div><b>Địa chỉ:</b> {{ $a->schedule->post->address }}</div>
                    <br>
                    <div><b>Thời gian:</b> {{ $a->schedule->time }}</div>
                    <br>
                    <div><b>Schedule for:</b> {{ $a->schedule->mode }}</div>
                    </div>
                    <br>
                    <div><b>Attendees:</b>
                        @foreach($a->schedule->attendee as $attendee)
                        <br>
                        <img src="{{ $attendee->user->info->avatar ?? asset('picture/blank-img.png') }}" width="5%" height="5%"
                        style="border-radius: 50% 50% 50% 50%">
                        <a href="{{ route('lostintaste.profile', ['id' => $attendee->user->id]) }}">
                            {{ $attendee->user->name }}
                        </a>
                        @endforeach
                    </div>
                    <br>
                    <div><h6>Cập nhật lúc: {{ $a->schedule->updated_at }}</h6></div>
                    <div class="row">
                        <div class="col">
                            <a href="{{ route('lostintaste.delete_attendee', ['id' => $a->id]) }}" style="text-decoration: none">
                                <button class="btn btn-outline-danger">Hủy tham gia</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            @endforeach
        </div>
    </div>
@endsection