routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Post;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'Controller@aboutMe');

//LostinTaste Module
Route::prefix('lostintaste')->name('lostintaste.')->group(function() {
    
    // welcome's route
    Route::get('/', 'LostinTaste\HomeController@index')->name('welcome');
    Route::get('searcher', 'LostinTaste\HomeController@search')->name('searcher');
    Route::get('getprovince/{district}', 'LostinTaste\HomeController@getProvince');
    Route::get('getfood', 'LostinTaste\HomeController@getFood');

    // user's routes
    Route::get('me', 'LostinTaste\HomeController@selfInfo')->name('self_info');
    Route::get('profile/{id}', 'LostinTaste\HomeController@userProfile')->name('profile');
    Route::get('update/user/{id}', 'LostinTaste\HomeController@updateUser')->name('update_user');
    Route::post('update/user', 'LostinTaste\HomeController@insertUser')->name('insert_user');

    // news's routes
    Route::get('news', 'LostinTaste\HomeController@news')->name('news');
    Route::get('attend/{id}', 'LostinTaste\HomeController@attend');

    // post's routes
    Route::get('post', 'LostinTaste\HomeController@post')->name('post');
    Route::get('newpost', 'LostinTaste\HomeController@newPost')->name('new_post');
    Route::get('update/post/{id}', 'LostinTaste\HomeController@updatePost');
    Route::post('insertpost', 'LostinTaste\HomeController@insertPost')->name('insert_post');
    Route::get('delete/post/{id}', 'LostinTaste\HomeController@deletePost');

    // savedpost's routes
    Route::get('savedpost', 'LostinTaste\HomeController@savedpost')->name('savedpost');
    Route::get('newsavedpost/{id}', 'LostinTaste\HomeController@newSavedpost');
    Route::get('update/savedpost/{id}/{mode}', 'LostinTaste\HomeController@updateSavedpost');
    Route::get('delete/savedpost/{id}', 'LostinTaste\HomeController@deleteSavedpost');

    // schedule's routes
    Route::get('schedule', 'LostinTaste\HomeController@schedule')->name('schedule');
    Route::get('newschedule/{id}', 'LostinTaste\HomeController@newSchedule');
    Route::get('update/schedule/{id}', 'LostinTaste\HomeController@updateSchedule');
    Route::post('insertschedule', 'LostinTaste\HomeController@insertSchedule')->name('insert_schedule');
    Route::get('delete/schedule/{id}', 'LostinTaste\HomeController@deleteSchedule');

    Route::get('delete/attendee/{id}', 'LostinTaste\HomeController@deleteAttendee')->name('delete_attendee');

    // friend's routes
    Route::get('friend', 'LostinTaste\HomeController@friend')->name('friend');
    Route::get('search-friend/{input?}', 'LostinTaste\HomeController@searchFriend')->name('search_friend');
    Route::get('addfriend/{id}', 'LostinTaste\HomeController@addfriend')->name('add_friend');
    Route::get('dropfriend/{id}', 'LostinTaste\HomeController@dropfriend')->name('drop_friend');

    // message's routes
    Route::get('message', 'LostinTaste\HomeController@message')->name('message');
    Route::get('inbox/{id?}', 'LostinTaste\HomeController@inbox')->name('inbox');
    Route::get('sendmessage', 'LostinTaste\HomeController@sendMessage')->name('send_message');
    Route::get('refresh/{id}', 'LostinTaste\HomeController@refresh')->name('refresh');

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow">
	<meta name="keywords" content="Lostintaste">
	<meta name="description" content="Một trang web tìm đồ ăn cho những cô cậu sinh viên">
	<meta property="og:title" content="Lostintaste">
	<meta property="og:url" content="//lostintaste.epizy.com">
	<meta property="og:type" content="product">
	<meta name="DC.language" content="scheme=utf-8 content=vi">
	<meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE">
	<meta name="google-site-verification" content="">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Lost in Taste</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<style>
    html{
        scroll-behavior: smooth;
        background-color: #6BBDEE;
        background-image: linear-gradient(135deg, #6BBDEE, white);
    }
    #app{
        background-color: #6BBDEE;
        background-image: linear-gradient(135deg, #6BBDEE, white);
    }
    .reddot{
        background-color: red; 
        border-radius: 50% 50% 50% 50%;
        position: absolute;
        right: 5%;
        top: 0%;
        transform: scale(0.5) ;
        width: 10%;
    }
    .bg-yum{
        background-color: #F0B28D;
        background-image: linear-gradient(white, #6BBDEE);
    }
    div{
        text-align: center;
    }
</style>
<body>
    @extends('vue-apps', ['exclude' => 'app'])
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-yum shadow-lg pb-5">
            <div class="container">
                <a class="navbar-brand" href="{{ route('lostintaste.welcome') }}">
                    <h3>Lost in Taste</h3>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <div class="dropdown">
                        <!-- Authentication Links -->
                        @guest
                            
                                <a class="dropdown-item" href="{{ route('login') }}">{{ __('Login') }}</a>
                            
                            @if (Route::has('register'))
                                
                                    <a class="dropdown-item" href="{{ route('register') }}">{{ __('Register') }}</a>
                                
                            @endif
                        @else
                            <div class="navbar-item dropdown">
                                <a href="{{ route('lostintaste.self_info') }}">{{ Auth::user()->name }}</a>

                                <div class="" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </div>
                        @endguest
                        
                        </div>
                </div>
            </div>
        </nav>
        <div class=""></div>
        <main class="py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        @yield('content')
                    </div>
                </div>
            </div>
        </main>
    </div>
    <a href="#" style="left: 80%; top: 95%" class="fixed-bottom" ><button class="btn btn-outline-danger">Go Up</button></a>
    @yield('script')
</body>
</html>